runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /article/res
  static_dir: articles/res
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
